mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    username: root
    password: 144125236
    url: jdbc:mysql://localhost:3306/community
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 0
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true