mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    username: root
    password: 144125236
    url: jdbc:mysql://localhost:3306/community
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      aop-patterns: com.community.controller.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false
        url-pattern: "/druid/*"
      web-stat-filter: # 监控web
        enabled: true
        urlPattern: "/*"
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  thymeleaf:
    enabled: true
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 0
  servlet:
    multipart:
      max-file-size: 5MB
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true